spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            #数据源1
            url: jdbc:mysql://localhost:3306/dream_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
            driver-class-name: com.mysql.jdbc.Driver
            username: root
            password: 123456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true
# mache

memcached:
    ip: 192.168.1.6
    port: 11211
is:
  dev: true
online:
    domain: http://192.168.1.9:8080